language: go
go:
 - "1.8.x"

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  - echo $GCLOUD_SERVICE_KEY > key.json
  - gcloud auth activate-service-account --key-file key.json

script:
  - make deploy
  - gsutil cp release.zip $GCLOUD_ARTEFACTS_BUCKET/$TRAVIS_TAG.zip

cache:
  directories:
    - "$HOME/google-cloud-sdk/"