steps:
- name: 'gcr.io/$PROJECT_ID/dep'
  args:  ['ensure', '-v']
  env: ['PROJECT_ROOT=github.com/raphael-trzpit/poll']
- name: 'gcr.io/$PROJECT_ID/make'
  args: ['prepare-deploy']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--no-promote', '--version=1-7', 'src/app.yaml']
  env:
    - 'GOPATH=/workspace'
